/*Data from gl.xml, which has this copyright:

#Copyright (c) 2013-2016 The Khronos Group Inc.
#
#Permission is hereby granted, free of charge, to any person obtaining a
#copy of this software and/or associated documentation files (the
#"Materials"), to deal in the Materials without restriction, including
#without limitation the rights to use, copy, modify, merge, publish,
#distribute, sublicense, and/or sell copies of the Materials, and to
#permit persons to whom the Materials are furnished to do so, subject to
#the following conditions:
#
#The above copyright notice and this permission notice shall be included
#in all copies or substantial portions of the Materials.
#
#THE MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.
#
#------------------------------------------------------------------------
#
#This file, gl.xml, is the OpenGL and OpenGL API Registry. The older
#".spec" file format has been retired and will no longer be updated with
#new extensions and API versions. The canonical version of the registry,
#together with documentation, schema, and Python generator scripts used
#to generate C header files for OpenGL and OpenGL ES, can always be found
#in the Khronos Registry at
#        http://www.opengl.org/registry/
#    
*/
#pragma once
#include "glcorearb.h"
void glActiveShaderProgram (GLuint pipeline_ , GLuint program_ );
void glActiveTexture (GLenum texture_ );
void glAttachShader (GLuint program_ , GLuint shader_ );
void glBeginConditionalRender (GLuint id_ , GLenum mode_ );
void glBeginQuery (GLenum target_ , GLuint id_ );
void glBeginQueryIndexed (GLenum target_ , GLuint index_ , GLuint id_ );
void glBeginTransformFeedback (GLenum primitiveMode_ );
void glBindAttribLocation (GLuint program_ , GLuint index_ , const GLchar * name_ );
void glBindBuffer (GLenum target_ , GLuint buffer_ );
void glBindBufferBase (GLenum target_ , GLuint index_ , GLuint buffer_ );
void glBindBufferRange (GLenum target_ , GLuint index_ , GLuint buffer_ , GLintptr offset_ , GLsizeiptr size_ );
void glBindBuffersBase (GLenum target_ , GLuint first_ , GLsizei count_ , const GLuint * buffers_ );
void glBindBuffersRange (GLenum target_ , GLuint first_ , GLsizei count_ , const GLuint * buffers_ , const GLintptr * offsets_ , const GLsizeiptr * sizes_ );
void glBindFragDataLocation (GLuint program_ , GLuint color_ , const GLchar * name_ );
void glBindFragDataLocationIndexed (GLuint program_ , GLuint colorNumber_ , GLuint index_ , const GLchar * name_ );
void glBindFramebuffer (GLenum target_ , GLuint framebuffer_ );
void glBindImageTexture (GLuint unit_ , GLuint texture_ , GLint level_ , GLboolean layered_ , GLint layer_ , GLenum access_ , GLenum format_ );
void glBindImageTextures (GLuint first_ , GLsizei count_ , const GLuint * textures_ );
void glBindProgramPipeline (GLuint pipeline_ );
void glBindRenderbuffer (GLenum target_ , GLuint renderbuffer_ );
void glBindSampler (GLuint unit_ , GLuint sampler_ );
void glBindSamplers (GLuint first_ , GLsizei count_ , const GLuint * samplers_ );
void glBindTexture (GLenum target_ , GLuint texture_ );
void glBindTextureUnit (GLuint unit_ , GLuint texture_ );
void glBindTextures (GLuint first_ , GLsizei count_ , const GLuint * textures_ );
void glBindTransformFeedback (GLenum target_ , GLuint id_ );
void glBindVertexArray (GLuint array_ );
void glBindVertexBuffer (GLuint bindingindex_ , GLuint buffer_ , GLintptr offset_ , GLsizei stride_ );
void glBindVertexBuffers (GLuint first_ , GLsizei count_ , const GLuint * buffers_ , const GLintptr * offsets_ , const GLsizei * strides_ );
void glBlendColor (GLfloat red_ , GLfloat green_ , GLfloat blue_ , GLfloat alpha_ );
void glBlendEquation (GLenum mode_ );
void glBlendEquationSeparate (GLenum modeRGB_ , GLenum modeAlpha_ );
void glBlendEquationSeparatei (GLuint buf_ , GLenum modeRGB_ , GLenum modeAlpha_ );
void glBlendEquationi (GLuint buf_ , GLenum mode_ );
void glBlendFunc (GLenum sfactor_ , GLenum dfactor_ );
void glBlendFuncSeparate (GLenum sfactorRGB_ , GLenum dfactorRGB_ , GLenum sfactorAlpha_ , GLenum dfactorAlpha_ );
void glBlendFuncSeparatei (GLuint buf_ , GLenum srcRGB_ , GLenum dstRGB_ , GLenum srcAlpha_ , GLenum dstAlpha_ );
void glBlendFunci (GLuint buf_ , GLenum src_ , GLenum dst_ );
void glBlitFramebuffer (GLint srcX0_ , GLint srcY0_ , GLint srcX1_ , GLint srcY1_ , GLint dstX0_ , GLint dstY0_ , GLint dstX1_ , GLint dstY1_ , GLbitfield mask_ , GLenum filter_ );
void glBlitNamedFramebuffer (GLuint readFramebuffer_ , GLuint drawFramebuffer_ , GLint srcX0_ , GLint srcY0_ , GLint srcX1_ , GLint srcY1_ , GLint dstX0_ , GLint dstY0_ , GLint dstX1_ , GLint dstY1_ , GLbitfield mask_ , GLenum filter_ );
void glBufferData (GLenum target_ , GLsizeiptr size_ , const void * data_ , GLenum usage_ );
void glBufferStorage (GLenum target_ , GLsizeiptr size_ , const void * data_ , GLbitfield flags_ );
void glBufferSubData (GLenum target_ , GLintptr offset_ , GLsizeiptr size_ , const void * data_ );
GLenum glCheckFramebufferStatus (GLenum target_ );
GLenum glCheckNamedFramebufferStatus (GLuint framebuffer_ , GLenum target_ );
void glClampColor (GLenum target_ , GLenum clamp_ );
void glClear (GLbitfield mask_ );
void glClearBufferData (GLenum target_ , GLenum internalformat_ , GLenum format_ , GLenum type_ , const void * data_ );
void glClearBufferSubData (GLenum target_ , GLenum internalformat_ , GLintptr offset_ , GLsizeiptr size_ , GLenum format_ , GLenum type_ , const void * data_ );
void glClearBufferfi (GLenum buffer_ , GLint drawbuffer_ , GLfloat depth_ , GLint stencil_ );
void glClearBufferfv (GLenum buffer_ , GLint drawbuffer_ , const GLfloat * value_ );
void glClearBufferiv (GLenum buffer_ , GLint drawbuffer_ , const GLint * value_ );
void glClearBufferuiv (GLenum buffer_ , GLint drawbuffer_ , const GLuint * value_ );
void glClearColor (GLfloat red_ , GLfloat green_ , GLfloat blue_ , GLfloat alpha_ );
void glClearDepth (GLdouble depth_ );
void glClearDepthf (GLfloat d_ );
void glClearNamedBufferData (GLuint buffer_ , GLenum internalformat_ , GLenum format_ , GLenum type_ , const void * data_ );
void glClearNamedBufferSubData (GLuint buffer_ , GLenum internalformat_ , GLintptr offset_ , GLsizeiptr size_ , GLenum format_ , GLenum type_ , const void * data_ );
void glClearNamedFramebufferfi (GLuint framebuffer_ , GLenum buffer_ , GLint drawbuffer_ , GLfloat depth_ , GLint stencil_ );
void glClearNamedFramebufferfv (GLuint framebuffer_ , GLenum buffer_ , GLint drawbuffer_ , const GLfloat * value_ );
void glClearNamedFramebufferiv (GLuint framebuffer_ , GLenum buffer_ , GLint drawbuffer_ , const GLint * value_ );
void glClearNamedFramebufferuiv (GLuint framebuffer_ , GLenum buffer_ , GLint drawbuffer_ , const GLuint * value_ );
void glClearStencil (GLint s_ );
void glClearTexImage (GLuint texture_ , GLint level_ , GLenum format_ , GLenum type_ , const void * data_ );
void glClearTexSubImage (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLenum format_ , GLenum type_ , const void * data_ );
GLenum glClientWaitSync (GLsync sync_ , GLbitfield flags_ , GLuint64 timeout_ );
void glClipControl (GLenum origin_ , GLenum depth_ );
void glColorMask (GLboolean red_ , GLboolean green_ , GLboolean blue_ , GLboolean alpha_ );
void glColorMaski (GLuint index_ , GLboolean r_ , GLboolean g_ , GLboolean b_ , GLboolean a_ );
void glCompileShader (GLuint shader_ );
void glCompressedTexImage1D (GLenum target_ , GLint level_ , GLenum internalformat_ , GLsizei width_ , GLint border_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTexImage2D (GLenum target_ , GLint level_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ , GLint border_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTexImage3D (GLenum target_ , GLint level_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLint border_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTexSubImage1D (GLenum target_ , GLint level_ , GLint xoffset_ , GLsizei width_ , GLenum format_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTexSubImage2D (GLenum target_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLsizei width_ , GLsizei height_ , GLenum format_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTexSubImage3D (GLenum target_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLenum format_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTextureSubImage1D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLsizei width_ , GLenum format_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTextureSubImage2D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLsizei width_ , GLsizei height_ , GLenum format_ , GLsizei imageSize_ , const void * data_ );
void glCompressedTextureSubImage3D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLenum format_ , GLsizei imageSize_ , const void * data_ );
void glCopyBufferSubData (GLenum readTarget_ , GLenum writeTarget_ , GLintptr readOffset_ , GLintptr writeOffset_ , GLsizeiptr size_ );
void glCopyImageSubData (GLuint srcName_ , GLenum srcTarget_ , GLint srcLevel_ , GLint srcX_ , GLint srcY_ , GLint srcZ_ , GLuint dstName_ , GLenum dstTarget_ , GLint dstLevel_ , GLint dstX_ , GLint dstY_ , GLint dstZ_ , GLsizei srcWidth_ , GLsizei srcHeight_ , GLsizei srcDepth_ );
void glCopyNamedBufferSubData (GLuint readBuffer_ , GLuint writeBuffer_ , GLintptr readOffset_ , GLintptr writeOffset_ , GLsizeiptr size_ );
void glCopyTexImage1D (GLenum target_ , GLint level_ , GLenum internalformat_ , GLint x_ , GLint y_ , GLsizei width_ , GLint border_ );
void glCopyTexImage2D (GLenum target_ , GLint level_ , GLenum internalformat_ , GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ , GLint border_ );
void glCopyTexSubImage1D (GLenum target_ , GLint level_ , GLint xoffset_ , GLint x_ , GLint y_ , GLsizei width_ );
void glCopyTexSubImage2D (GLenum target_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glCopyTexSubImage3D (GLenum target_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glCopyTextureSubImage1D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint x_ , GLint y_ , GLsizei width_ );
void glCopyTextureSubImage2D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glCopyTextureSubImage3D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glCreateBuffers (GLsizei n_ , GLuint * buffers_ );
void glCreateFramebuffers (GLsizei n_ , GLuint * framebuffers_ );
GLuint glCreateProgram ();
void glCreateProgramPipelines (GLsizei n_ , GLuint * pipelines_ );
void glCreateQueries (GLenum target_ , GLsizei n_ , GLuint * ids_ );
void glCreateRenderbuffers (GLsizei n_ , GLuint * renderbuffers_ );
void glCreateSamplers (GLsizei n_ , GLuint * samplers_ );
GLuint glCreateShader (GLenum type_ );
GLuint glCreateShaderProgramv (GLenum type_ , GLsizei count_ , const GLchar ** strings_ );
void glCreateTextures (GLenum target_ , GLsizei n_ , GLuint * textures_ );
void glCreateTransformFeedbacks (GLsizei n_ , GLuint * ids_ );
void glCreateVertexArrays (GLsizei n_ , GLuint * arrays_ );
void glCullFace (GLenum mode_ );
void glDebugMessageCallback (GLDEBUGPROC callback_ , const void * userParam_ );
void glDebugMessageControl (GLenum source_ , GLenum type_ , GLenum severity_ , GLsizei count_ , const GLuint * ids_ , GLboolean enabled_ );
void glDebugMessageInsert (GLenum source_ , GLenum type_ , GLuint id_ , GLenum severity_ , GLsizei length_ , const GLchar * buf_ );
void glDeleteBuffers (GLsizei n_ , const GLuint * buffers_ );
void glDeleteFramebuffers (GLsizei n_ , const GLuint * framebuffers_ );
void glDeleteProgram (GLuint program_ );
void glDeleteProgramPipelines (GLsizei n_ , const GLuint * pipelines_ );
void glDeleteQueries (GLsizei n_ , const GLuint * ids_ );
void glDeleteRenderbuffers (GLsizei n_ , const GLuint * renderbuffers_ );
void glDeleteSamplers (GLsizei count_ , const GLuint * samplers_ );
void glDeleteShader (GLuint shader_ );
void glDeleteSync (GLsync sync_ );
void glDeleteTextures (GLsizei n_ , const GLuint * textures_ );
void glDeleteTransformFeedbacks (GLsizei n_ , const GLuint * ids_ );
void glDeleteVertexArrays (GLsizei n_ , const GLuint * arrays_ );
void glDepthFunc (GLenum func_ );
void glDepthMask (GLboolean flag_ );
void glDepthRange (GLdouble near_ , GLdouble far_ );
void glDepthRangeArrayv (GLuint first_ , GLsizei count_ , const GLdouble * v_ );
void glDepthRangeIndexed (GLuint index_ , GLdouble n_ , GLdouble f_ );
void glDepthRangef (GLfloat n_ , GLfloat f_ );
void glDetachShader (GLuint program_ , GLuint shader_ );
void glDisable (GLenum cap_ );
void glDisableVertexArrayAttrib (GLuint vaobj_ , GLuint index_ );
void glDisableVertexAttribArray (GLuint index_ );
void glDisablei (GLenum target_ , GLuint index_ );
void glDispatchCompute (GLuint num_groups_x_ , GLuint num_groups_y_ , GLuint num_groups_z_ );
void glDispatchComputeIndirect (GLintptr indirect_ );
void glDrawArrays (GLenum mode_ , GLint first_ , GLsizei count_ );
void glDrawArraysIndirect (GLenum mode_ , const void * indirect_ );
void glDrawArraysInstanced (GLenum mode_ , GLint first_ , GLsizei count_ , GLsizei instancecount_ );
void glDrawArraysInstancedBaseInstance (GLenum mode_ , GLint first_ , GLsizei count_ , GLsizei instancecount_ , GLuint baseinstance_ );
void glDrawBuffer (GLenum buf_ );
void glDrawBuffers (GLsizei n_ , const GLenum * bufs_ );
void glDrawElements (GLenum mode_ , GLsizei count_ , GLenum type_ , const void * indices_ );
void glDrawElementsBaseVertex (GLenum mode_ , GLsizei count_ , GLenum type_ , const void * indices_ , GLint basevertex_ );
void glDrawElementsIndirect (GLenum mode_ , GLenum type_ , const void * indirect_ );
void glDrawElementsInstanced (GLenum mode_ , GLsizei count_ , GLenum type_ , const void * indices_ , GLsizei instancecount_ );
void glDrawElementsInstancedBaseInstance (GLenum mode_ , GLsizei count_ , GLenum type_ , const void * indices_ , GLsizei instancecount_ , GLuint baseinstance_ );
void glDrawElementsInstancedBaseVertex (GLenum mode_ , GLsizei count_ , GLenum type_ , const void * indices_ , GLsizei instancecount_ , GLint basevertex_ );
void glDrawElementsInstancedBaseVertexBaseInstance (GLenum mode_ , GLsizei count_ , GLenum type_ , const void * indices_ , GLsizei instancecount_ , GLint basevertex_ , GLuint baseinstance_ );
void glDrawRangeElements (GLenum mode_ , GLuint start_ , GLuint end_ , GLsizei count_ , GLenum type_ , const void * indices_ );
void glDrawRangeElementsBaseVertex (GLenum mode_ , GLuint start_ , GLuint end_ , GLsizei count_ , GLenum type_ , const void * indices_ , GLint basevertex_ );
void glDrawTransformFeedback (GLenum mode_ , GLuint id_ );
void glDrawTransformFeedbackInstanced (GLenum mode_ , GLuint id_ , GLsizei instancecount_ );
void glDrawTransformFeedbackStream (GLenum mode_ , GLuint id_ , GLuint stream_ );
void glDrawTransformFeedbackStreamInstanced (GLenum mode_ , GLuint id_ , GLuint stream_ , GLsizei instancecount_ );
void glEnable (GLenum cap_ );
void glEnableVertexArrayAttrib (GLuint vaobj_ , GLuint index_ );
void glEnableVertexAttribArray (GLuint index_ );
void glEnablei (GLenum target_ , GLuint index_ );
void glEndConditionalRender ();
void glEndQuery (GLenum target_ );
void glEndQueryIndexed (GLenum target_ , GLuint index_ );
void glEndTransformFeedback ();
GLsync glFenceSync (GLenum condition_ , GLbitfield flags_ );
void glFinish ();
void glFlush ();
void glFlushMappedBufferRange (GLenum target_ , GLintptr offset_ , GLsizeiptr length_ );
void glFlushMappedNamedBufferRange (GLuint buffer_ , GLintptr offset_ , GLsizeiptr length_ );
void glFramebufferParameteri (GLenum target_ , GLenum pname_ , GLint param_ );
void glFramebufferRenderbuffer (GLenum target_ , GLenum attachment_ , GLenum renderbuffertarget_ , GLuint renderbuffer_ );
void glFramebufferTexture (GLenum target_ , GLenum attachment_ , GLuint texture_ , GLint level_ );
void glFramebufferTexture1D (GLenum target_ , GLenum attachment_ , GLenum textarget_ , GLuint texture_ , GLint level_ );
void glFramebufferTexture2D (GLenum target_ , GLenum attachment_ , GLenum textarget_ , GLuint texture_ , GLint level_ );
void glFramebufferTexture3D (GLenum target_ , GLenum attachment_ , GLenum textarget_ , GLuint texture_ , GLint level_ , GLint zoffset_ );
void glFramebufferTextureLayer (GLenum target_ , GLenum attachment_ , GLuint texture_ , GLint level_ , GLint layer_ );
void glFrontFace (GLenum mode_ );
void glGenBuffers (GLsizei n_ , GLuint * buffers_ );
void glGenFramebuffers (GLsizei n_ , GLuint * framebuffers_ );
void glGenProgramPipelines (GLsizei n_ , GLuint * pipelines_ );
void glGenQueries (GLsizei n_ , GLuint * ids_ );
void glGenRenderbuffers (GLsizei n_ , GLuint * renderbuffers_ );
void glGenSamplers (GLsizei count_ , GLuint * samplers_ );
void glGenTextures (GLsizei n_ , GLuint * textures_ );
void glGenTransformFeedbacks (GLsizei n_ , GLuint * ids_ );
void glGenVertexArrays (GLsizei n_ , GLuint * arrays_ );
void glGenerateMipmap (GLenum target_ );
void glGenerateTextureMipmap (GLuint texture_ );
void glGetActiveAtomicCounterBufferiv (GLuint program_ , GLuint bufferIndex_ , GLenum pname_ , GLint * params_ );
void glGetActiveAttrib (GLuint program_ , GLuint index_ , GLsizei bufSize_ , GLsizei * length_ , GLint * size_ , GLenum * type_ , GLchar * name_ );
void glGetActiveSubroutineName (GLuint program_ , GLenum shadertype_ , GLuint index_ , GLsizei bufsize_ , GLsizei * length_ , GLchar * name_ );
void glGetActiveSubroutineUniformName (GLuint program_ , GLenum shadertype_ , GLuint index_ , GLsizei bufsize_ , GLsizei * length_ , GLchar * name_ );
void glGetActiveSubroutineUniformiv (GLuint program_ , GLenum shadertype_ , GLuint index_ , GLenum pname_ , GLint * values_ );
void glGetActiveUniform (GLuint program_ , GLuint index_ , GLsizei bufSize_ , GLsizei * length_ , GLint * size_ , GLenum * type_ , GLchar * name_ );
void glGetActiveUniformBlockName (GLuint program_ , GLuint uniformBlockIndex_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * uniformBlockName_ );
void glGetActiveUniformBlockiv (GLuint program_ , GLuint uniformBlockIndex_ , GLenum pname_ , GLint * params_ );
void glGetActiveUniformName (GLuint program_ , GLuint uniformIndex_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * uniformName_ );
void glGetActiveUniformsiv (GLuint program_ , GLsizei uniformCount_ , const GLuint * uniformIndices_ , GLenum pname_ , GLint * params_ );
void glGetAttachedShaders (GLuint program_ , GLsizei maxCount_ , GLsizei * count_ , GLuint * shaders_ );
GLint glGetAttribLocation (GLuint program_ , const GLchar * name_ );
void glGetBooleani_v (GLenum target_ , GLuint index_ , GLboolean * data_ );
void glGetBooleanv (GLenum pname_ , GLboolean * data_ );
void glGetBufferParameteri64v (GLenum target_ , GLenum pname_ , GLint64 * params_ );
void glGetBufferParameteriv (GLenum target_ , GLenum pname_ , GLint * params_ );
void glGetBufferPointerv (GLenum target_ , GLenum pname_ , void ** params_ );
void glGetBufferSubData (GLenum target_ , GLintptr offset_ , GLsizeiptr size_ , void * data_ );
void glGetCompressedTexImage (GLenum target_ , GLint level_ , void * img_ );
void glGetCompressedTextureImage (GLuint texture_ , GLint level_ , GLsizei bufSize_ , void * pixels_ );
void glGetCompressedTextureSubImage (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLsizei bufSize_ , void * pixels_ );
GLuint glGetDebugMessageLog (GLuint count_ , GLsizei bufSize_ , GLenum * sources_ , GLenum * types_ , GLuint * ids_ , GLenum * severities_ , GLsizei * lengths_ , GLchar * messageLog_ );
void glGetDoublei_v (GLenum target_ , GLuint index_ , GLdouble * data_ );
void glGetDoublev (GLenum pname_ , GLdouble * data_ );
GLenum glGetError ();
void glGetFloati_v (GLenum target_ , GLuint index_ , GLfloat * data_ );
void glGetFloatv (GLenum pname_ , GLfloat * data_ );
GLint glGetFragDataIndex (GLuint program_ , const GLchar * name_ );
GLint glGetFragDataLocation (GLuint program_ , const GLchar * name_ );
void glGetFramebufferAttachmentParameteriv (GLenum target_ , GLenum attachment_ , GLenum pname_ , GLint * params_ );
void glGetFramebufferParameteriv (GLenum target_ , GLenum pname_ , GLint * params_ );
GLenum glGetGraphicsResetStatus ();
void glGetInteger64i_v (GLenum target_ , GLuint index_ , GLint64 * data_ );
void glGetInteger64v (GLenum pname_ , GLint64 * data_ );
void glGetIntegeri_v (GLenum target_ , GLuint index_ , GLint * data_ );
void glGetIntegerv (GLenum pname_ , GLint * data_ );
void glGetInternalformati64v (GLenum target_ , GLenum internalformat_ , GLenum pname_ , GLsizei bufSize_ , GLint64 * params_ );
void glGetInternalformativ (GLenum target_ , GLenum internalformat_ , GLenum pname_ , GLsizei bufSize_ , GLint * params_ );
void glGetMultisamplefv (GLenum pname_ , GLuint index_ , GLfloat * val_ );
void glGetNamedBufferParameteri64v (GLuint buffer_ , GLenum pname_ , GLint64 * params_ );
void glGetNamedBufferParameteriv (GLuint buffer_ , GLenum pname_ , GLint * params_ );
void glGetNamedBufferPointerv (GLuint buffer_ , GLenum pname_ , void ** params_ );
void glGetNamedBufferSubData (GLuint buffer_ , GLintptr offset_ , GLsizeiptr size_ , void * data_ );
void glGetNamedFramebufferAttachmentParameteriv (GLuint framebuffer_ , GLenum attachment_ , GLenum pname_ , GLint * params_ );
void glGetNamedFramebufferParameteriv (GLuint framebuffer_ , GLenum pname_ , GLint * param_ );
void glGetNamedRenderbufferParameteriv (GLuint renderbuffer_ , GLenum pname_ , GLint * params_ );
void glGetObjectLabel (GLenum identifier_ , GLuint name_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * label_ );
void glGetObjectPtrLabel (const void * ptr_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * label_ );
void glGetProgramBinary (GLuint program_ , GLsizei bufSize_ , GLsizei * length_ , GLenum * binaryFormat_ , void * binary_ );
void glGetProgramInfoLog (GLuint program_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * infoLog_ );
void glGetProgramInterfaceiv (GLuint program_ , GLenum programInterface_ , GLenum pname_ , GLint * params_ );
void glGetProgramPipelineInfoLog (GLuint pipeline_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * infoLog_ );
void glGetProgramPipelineiv (GLuint pipeline_ , GLenum pname_ , GLint * params_ );
GLuint glGetProgramResourceIndex (GLuint program_ , GLenum programInterface_ , const GLchar * name_ );
GLint glGetProgramResourceLocation (GLuint program_ , GLenum programInterface_ , const GLchar * name_ );
GLint glGetProgramResourceLocationIndex (GLuint program_ , GLenum programInterface_ , const GLchar * name_ );
void glGetProgramResourceName (GLuint program_ , GLenum programInterface_ , GLuint index_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * name_ );
void glGetProgramResourceiv (GLuint program_ , GLenum programInterface_ , GLuint index_ , GLsizei propCount_ , const GLenum * props_ , GLsizei bufSize_ , GLsizei * length_ , GLint * params_ );
void glGetProgramStageiv (GLuint program_ , GLenum shadertype_ , GLenum pname_ , GLint * values_ );
void glGetProgramiv (GLuint program_ , GLenum pname_ , GLint * params_ );
void glGetQueryBufferObjecti64v (GLuint id_ , GLuint buffer_ , GLenum pname_ , GLintptr offset_ );
void glGetQueryBufferObjectiv (GLuint id_ , GLuint buffer_ , GLenum pname_ , GLintptr offset_ );
void glGetQueryBufferObjectui64v (GLuint id_ , GLuint buffer_ , GLenum pname_ , GLintptr offset_ );
void glGetQueryBufferObjectuiv (GLuint id_ , GLuint buffer_ , GLenum pname_ , GLintptr offset_ );
void glGetQueryIndexediv (GLenum target_ , GLuint index_ , GLenum pname_ , GLint * params_ );
void glGetQueryObjecti64v (GLuint id_ , GLenum pname_ , GLint64 * params_ );
void glGetQueryObjectiv (GLuint id_ , GLenum pname_ , GLint * params_ );
void glGetQueryObjectui64v (GLuint id_ , GLenum pname_ , GLuint64 * params_ );
void glGetQueryObjectuiv (GLuint id_ , GLenum pname_ , GLuint * params_ );
void glGetQueryiv (GLenum target_ , GLenum pname_ , GLint * params_ );
void glGetRenderbufferParameteriv (GLenum target_ , GLenum pname_ , GLint * params_ );
void glGetSamplerParameterIiv (GLuint sampler_ , GLenum pname_ , GLint * params_ );
void glGetSamplerParameterIuiv (GLuint sampler_ , GLenum pname_ , GLuint * params_ );
void glGetSamplerParameterfv (GLuint sampler_ , GLenum pname_ , GLfloat * params_ );
void glGetSamplerParameteriv (GLuint sampler_ , GLenum pname_ , GLint * params_ );
void glGetShaderInfoLog (GLuint shader_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * infoLog_ );
void glGetShaderPrecisionFormat (GLenum shadertype_ , GLenum precisiontype_ , GLint * range_ , GLint * precision_ );
void glGetShaderSource (GLuint shader_ , GLsizei bufSize_ , GLsizei * length_ , GLchar * source_ );
void glGetShaderiv (GLuint shader_ , GLenum pname_ , GLint * params_ );
const GLubyte * glGetString (GLenum name_ );
const GLubyte * glGetStringi (GLenum name_ , GLuint index_ );
GLuint glGetSubroutineIndex (GLuint program_ , GLenum shadertype_ , const GLchar * name_ );
GLint glGetSubroutineUniformLocation (GLuint program_ , GLenum shadertype_ , const GLchar * name_ );
void glGetSynciv (GLsync sync_ , GLenum pname_ , GLsizei bufSize_ , GLsizei * length_ , GLint * values_ );
void glGetTexImage (GLenum target_ , GLint level_ , GLenum format_ , GLenum type_ , void * pixels_ );
void glGetTexLevelParameterfv (GLenum target_ , GLint level_ , GLenum pname_ , GLfloat * params_ );
void glGetTexLevelParameteriv (GLenum target_ , GLint level_ , GLenum pname_ , GLint * params_ );
void glGetTexParameterIiv (GLenum target_ , GLenum pname_ , GLint * params_ );
void glGetTexParameterIuiv (GLenum target_ , GLenum pname_ , GLuint * params_ );
void glGetTexParameterfv (GLenum target_ , GLenum pname_ , GLfloat * params_ );
void glGetTexParameteriv (GLenum target_ , GLenum pname_ , GLint * params_ );
void glGetTextureImage (GLuint texture_ , GLint level_ , GLenum format_ , GLenum type_ , GLsizei bufSize_ , void * pixels_ );
void glGetTextureLevelParameterfv (GLuint texture_ , GLint level_ , GLenum pname_ , GLfloat * params_ );
void glGetTextureLevelParameteriv (GLuint texture_ , GLint level_ , GLenum pname_ , GLint * params_ );
void glGetTextureParameterIiv (GLuint texture_ , GLenum pname_ , GLint * params_ );
void glGetTextureParameterIuiv (GLuint texture_ , GLenum pname_ , GLuint * params_ );
void glGetTextureParameterfv (GLuint texture_ , GLenum pname_ , GLfloat * params_ );
void glGetTextureParameteriv (GLuint texture_ , GLenum pname_ , GLint * params_ );
void glGetTextureSubImage (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLenum format_ , GLenum type_ , GLsizei bufSize_ , void * pixels_ );
void glGetTransformFeedbackVarying (GLuint program_ , GLuint index_ , GLsizei bufSize_ , GLsizei * length_ , GLsizei * size_ , GLenum * type_ , GLchar * name_ );
void glGetTransformFeedbacki64_v (GLuint xfb_ , GLenum pname_ , GLuint index_ , GLint64 * param_ );
void glGetTransformFeedbacki_v (GLuint xfb_ , GLenum pname_ , GLuint index_ , GLint * param_ );
void glGetTransformFeedbackiv (GLuint xfb_ , GLenum pname_ , GLint * param_ );
GLuint glGetUniformBlockIndex (GLuint program_ , const GLchar * uniformBlockName_ );
void glGetUniformIndices (GLuint program_ , GLsizei uniformCount_ , const GLchar ** uniformNames_ , GLuint * uniformIndices_ );
GLint glGetUniformLocation (GLuint program_ , const GLchar * name_ );
void glGetUniformSubroutineuiv (GLenum shadertype_ , GLint location_ , GLuint * params_ );
void glGetUniformdv (GLuint program_ , GLint location_ , GLdouble * params_ );
void glGetUniformfv (GLuint program_ , GLint location_ , GLfloat * params_ );
void glGetUniformiv (GLuint program_ , GLint location_ , GLint * params_ );
void glGetUniformuiv (GLuint program_ , GLint location_ , GLuint * params_ );
void glGetVertexArrayIndexed64iv (GLuint vaobj_ , GLuint index_ , GLenum pname_ , GLint64 * param_ );
void glGetVertexArrayIndexediv (GLuint vaobj_ , GLuint index_ , GLenum pname_ , GLint * param_ );
void glGetVertexArrayiv (GLuint vaobj_ , GLenum pname_ , GLint * param_ );
void glGetVertexAttribIiv (GLuint index_ , GLenum pname_ , GLint * params_ );
void glGetVertexAttribIuiv (GLuint index_ , GLenum pname_ , GLuint * params_ );
void glGetVertexAttribLdv (GLuint index_ , GLenum pname_ , GLdouble * params_ );
void glGetVertexAttribPointerv (GLuint index_ , GLenum pname_ , void ** pointer_ );
void glGetVertexAttribdv (GLuint index_ , GLenum pname_ , GLdouble * params_ );
void glGetVertexAttribfv (GLuint index_ , GLenum pname_ , GLfloat * params_ );
void glGetVertexAttribiv (GLuint index_ , GLenum pname_ , GLint * params_ );
void glGetnCompressedTexImage (GLenum target_ , GLint lod_ , GLsizei bufSize_ , void * pixels_ );
void glGetnTexImage (GLenum target_ , GLint level_ , GLenum format_ , GLenum type_ , GLsizei bufSize_ , void * pixels_ );
void glGetnUniformdv (GLuint program_ , GLint location_ , GLsizei bufSize_ , GLdouble * params_ );
void glGetnUniformfv (GLuint program_ , GLint location_ , GLsizei bufSize_ , GLfloat * params_ );
void glGetnUniformiv (GLuint program_ , GLint location_ , GLsizei bufSize_ , GLint * params_ );
void glGetnUniformuiv (GLuint program_ , GLint location_ , GLsizei bufSize_ , GLuint * params_ );
void glHint (GLenum target_ , GLenum mode_ );
void glInvalidateBufferData (GLuint buffer_ );
void glInvalidateBufferSubData (GLuint buffer_ , GLintptr offset_ , GLsizeiptr length_ );
void glInvalidateFramebuffer (GLenum target_ , GLsizei numAttachments_ , const GLenum * attachments_ );
void glInvalidateNamedFramebufferData (GLuint framebuffer_ , GLsizei numAttachments_ , const GLenum * attachments_ );
void glInvalidateNamedFramebufferSubData (GLuint framebuffer_ , GLsizei numAttachments_ , const GLenum * attachments_ , GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glInvalidateSubFramebuffer (GLenum target_ , GLsizei numAttachments_ , const GLenum * attachments_ , GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glInvalidateTexImage (GLuint texture_ , GLint level_ );
void glInvalidateTexSubImage (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ );
GLboolean glIsBuffer (GLuint buffer_ );
GLboolean glIsEnabled (GLenum cap_ );
GLboolean glIsEnabledi (GLenum target_ , GLuint index_ );
GLboolean glIsFramebuffer (GLuint framebuffer_ );
GLboolean glIsProgram (GLuint program_ );
GLboolean glIsProgramPipeline (GLuint pipeline_ );
GLboolean glIsQuery (GLuint id_ );
GLboolean glIsRenderbuffer (GLuint renderbuffer_ );
GLboolean glIsSampler (GLuint sampler_ );
GLboolean glIsShader (GLuint shader_ );
GLboolean glIsSync (GLsync sync_ );
GLboolean glIsTexture (GLuint texture_ );
GLboolean glIsTransformFeedback (GLuint id_ );
GLboolean glIsVertexArray (GLuint array_ );
void glLineWidth (GLfloat width_ );
void glLinkProgram (GLuint program_ );
void glLogicOp (GLenum opcode_ );
void * glMapBuffer (GLenum target_ , GLenum access_ );
void * glMapBufferRange (GLenum target_ , GLintptr offset_ , GLsizeiptr length_ , GLbitfield access_ );
void * glMapNamedBuffer (GLuint buffer_ , GLenum access_ );
void * glMapNamedBufferRange (GLuint buffer_ , GLintptr offset_ , GLsizeiptr length_ , GLbitfield access_ );
void glMemoryBarrier (GLbitfield barriers_ );
void glMemoryBarrierByRegion (GLbitfield barriers_ );
void glMinSampleShading (GLfloat value_ );
void glMultiDrawArrays (GLenum mode_ , const GLint * first_ , const GLsizei * count_ , GLsizei drawcount_ );
void glMultiDrawArraysIndirect (GLenum mode_ , const void * indirect_ , GLsizei drawcount_ , GLsizei stride_ );
void glMultiDrawElements (GLenum mode_ , const GLsizei * count_ , GLenum type_ , const void ** indices_ , GLsizei drawcount_ );
void glMultiDrawElementsBaseVertex (GLenum mode_ , const GLsizei * count_ , GLenum type_ , const void ** indices_ , GLsizei drawcount_ , const GLint * basevertex_ );
void glMultiDrawElementsIndirect (GLenum mode_ , GLenum type_ , const void * indirect_ , GLsizei drawcount_ , GLsizei stride_ );
void glNamedBufferData (GLuint buffer_ , GLsizeiptr size_ , const void * data_ , GLenum usage_ );
void glNamedBufferStorage (GLuint buffer_ , GLsizeiptr size_ , const void * data_ , GLbitfield flags_ );
void glNamedBufferSubData (GLuint buffer_ , GLintptr offset_ , GLsizeiptr size_ , const void * data_ );
void glNamedFramebufferDrawBuffer (GLuint framebuffer_ , GLenum buf_ );
void glNamedFramebufferDrawBuffers (GLuint framebuffer_ , GLsizei n_ , const GLenum * bufs_ );
void glNamedFramebufferParameteri (GLuint framebuffer_ , GLenum pname_ , GLint param_ );
void glNamedFramebufferReadBuffer (GLuint framebuffer_ , GLenum src_ );
void glNamedFramebufferRenderbuffer (GLuint framebuffer_ , GLenum attachment_ , GLenum renderbuffertarget_ , GLuint renderbuffer_ );
void glNamedFramebufferTexture (GLuint framebuffer_ , GLenum attachment_ , GLuint texture_ , GLint level_ );
void glNamedFramebufferTextureLayer (GLuint framebuffer_ , GLenum attachment_ , GLuint texture_ , GLint level_ , GLint layer_ );
void glNamedRenderbufferStorage (GLuint renderbuffer_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ );
void glNamedRenderbufferStorageMultisample (GLuint renderbuffer_ , GLsizei samples_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ );
void glObjectLabel (GLenum identifier_ , GLuint name_ , GLsizei length_ , const GLchar * label_ );
void glObjectPtrLabel (const void * ptr_ , GLsizei length_ , const GLchar * label_ );
void glPatchParameterfv (GLenum pname_ , const GLfloat * values_ );
void glPatchParameteri (GLenum pname_ , GLint value_ );
void glPauseTransformFeedback ();
void glPixelStoref (GLenum pname_ , GLfloat param_ );
void glPixelStorei (GLenum pname_ , GLint param_ );
void glPointParameterf (GLenum pname_ , GLfloat param_ );
void glPointParameterfv (GLenum pname_ , const GLfloat * params_ );
void glPointParameteri (GLenum pname_ , GLint param_ );
void glPointParameteriv (GLenum pname_ , const GLint * params_ );
void glPointSize (GLfloat size_ );
void glPolygonMode (GLenum face_ , GLenum mode_ );
void glPolygonOffset (GLfloat factor_ , GLfloat units_ );
void glPopDebugGroup ();
void glPrimitiveRestartIndex (GLuint index_ );
void glProgramBinary (GLuint program_ , GLenum binaryFormat_ , const void * binary_ , GLsizei length_ );
void glProgramParameteri (GLuint program_ , GLenum pname_ , GLint value_ );
void glProgramUniform1d (GLuint program_ , GLint location_ , GLdouble v0_ );
void glProgramUniform1dv (GLuint program_ , GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glProgramUniform1f (GLuint program_ , GLint location_ , GLfloat v0_ );
void glProgramUniform1fv (GLuint program_ , GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glProgramUniform1i (GLuint program_ , GLint location_ , GLint v0_ );
void glProgramUniform1iv (GLuint program_ , GLint location_ , GLsizei count_ , const GLint * value_ );
void glProgramUniform1ui (GLuint program_ , GLint location_ , GLuint v0_ );
void glProgramUniform1uiv (GLuint program_ , GLint location_ , GLsizei count_ , const GLuint * value_ );
void glProgramUniform2d (GLuint program_ , GLint location_ , GLdouble v0_ , GLdouble v1_ );
void glProgramUniform2dv (GLuint program_ , GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glProgramUniform2f (GLuint program_ , GLint location_ , GLfloat v0_ , GLfloat v1_ );
void glProgramUniform2fv (GLuint program_ , GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glProgramUniform2i (GLuint program_ , GLint location_ , GLint v0_ , GLint v1_ );
void glProgramUniform2iv (GLuint program_ , GLint location_ , GLsizei count_ , const GLint * value_ );
void glProgramUniform2ui (GLuint program_ , GLint location_ , GLuint v0_ , GLuint v1_ );
void glProgramUniform2uiv (GLuint program_ , GLint location_ , GLsizei count_ , const GLuint * value_ );
void glProgramUniform3d (GLuint program_ , GLint location_ , GLdouble v0_ , GLdouble v1_ , GLdouble v2_ );
void glProgramUniform3dv (GLuint program_ , GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glProgramUniform3f (GLuint program_ , GLint location_ , GLfloat v0_ , GLfloat v1_ , GLfloat v2_ );
void glProgramUniform3fv (GLuint program_ , GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glProgramUniform3i (GLuint program_ , GLint location_ , GLint v0_ , GLint v1_ , GLint v2_ );
void glProgramUniform3iv (GLuint program_ , GLint location_ , GLsizei count_ , const GLint * value_ );
void glProgramUniform3ui (GLuint program_ , GLint location_ , GLuint v0_ , GLuint v1_ , GLuint v2_ );
void glProgramUniform3uiv (GLuint program_ , GLint location_ , GLsizei count_ , const GLuint * value_ );
void glProgramUniform4d (GLuint program_ , GLint location_ , GLdouble v0_ , GLdouble v1_ , GLdouble v2_ , GLdouble v3_ );
void glProgramUniform4dv (GLuint program_ , GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glProgramUniform4f (GLuint program_ , GLint location_ , GLfloat v0_ , GLfloat v1_ , GLfloat v2_ , GLfloat v3_ );
void glProgramUniform4fv (GLuint program_ , GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glProgramUniform4i (GLuint program_ , GLint location_ , GLint v0_ , GLint v1_ , GLint v2_ , GLint v3_ );
void glProgramUniform4iv (GLuint program_ , GLint location_ , GLsizei count_ , const GLint * value_ );
void glProgramUniform4ui (GLuint program_ , GLint location_ , GLuint v0_ , GLuint v1_ , GLuint v2_ , GLuint v3_ );
void glProgramUniform4uiv (GLuint program_ , GLint location_ , GLsizei count_ , const GLuint * value_ );
void glProgramUniformMatrix2dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix2fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix2x3dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix2x3fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix2x4dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix2x4fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix3dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix3fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix3x2dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix3x2fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix3x4dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix3x4fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix4dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix4fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix4x2dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix4x2fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProgramUniformMatrix4x3dv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glProgramUniformMatrix4x3fv (GLuint program_ , GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glProvokingVertex (GLenum mode_ );
void glPushDebugGroup (GLenum source_ , GLuint id_ , GLsizei length_ , const GLchar * message_ );
void glQueryCounter (GLuint id_ , GLenum target_ );
void glReadBuffer (GLenum src_ );
void glReadPixels (GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ , GLenum format_ , GLenum type_ , void * pixels_ );
void glReadnPixels (GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ , GLenum format_ , GLenum type_ , GLsizei bufSize_ , void * data_ );
void glReleaseShaderCompiler ();
void glRenderbufferStorage (GLenum target_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ );
void glRenderbufferStorageMultisample (GLenum target_ , GLsizei samples_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ );
void glResumeTransformFeedback ();
void glSampleCoverage (GLfloat value_ , GLboolean invert_ );
void glSampleMaski (GLuint maskNumber_ , GLbitfield mask_ );
void glSamplerParameterIiv (GLuint sampler_ , GLenum pname_ , const GLint * param_ );
void glSamplerParameterIuiv (GLuint sampler_ , GLenum pname_ , const GLuint * param_ );
void glSamplerParameterf (GLuint sampler_ , GLenum pname_ , GLfloat param_ );
void glSamplerParameterfv (GLuint sampler_ , GLenum pname_ , const GLfloat * param_ );
void glSamplerParameteri (GLuint sampler_ , GLenum pname_ , GLint param_ );
void glSamplerParameteriv (GLuint sampler_ , GLenum pname_ , const GLint * param_ );
void glScissor (GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glScissorArrayv (GLuint first_ , GLsizei count_ , const GLint * v_ );
void glScissorIndexed (GLuint index_ , GLint left_ , GLint bottom_ , GLsizei width_ , GLsizei height_ );
void glScissorIndexedv (GLuint index_ , const GLint * v_ );
void glShaderBinary (GLsizei count_ , const GLuint * shaders_ , GLenum binaryformat_ , const void * binary_ , GLsizei length_ );
void glShaderSource (GLuint shader_ , GLsizei count_ , const GLchar ** string_ , const GLint * length_ );
void glShaderStorageBlockBinding (GLuint program_ , GLuint storageBlockIndex_ , GLuint storageBlockBinding_ );
void glStencilFunc (GLenum func_ , GLint ref_ , GLuint mask_ );
void glStencilFuncSeparate (GLenum face_ , GLenum func_ , GLint ref_ , GLuint mask_ );
void glStencilMask (GLuint mask_ );
void glStencilMaskSeparate (GLenum face_ , GLuint mask_ );
void glStencilOp (GLenum fail_ , GLenum zfail_ , GLenum zpass_ );
void glStencilOpSeparate (GLenum face_ , GLenum sfail_ , GLenum dpfail_ , GLenum dppass_ );
void glTexBuffer (GLenum target_ , GLenum internalformat_ , GLuint buffer_ );
void glTexBufferRange (GLenum target_ , GLenum internalformat_ , GLuint buffer_ , GLintptr offset_ , GLsizeiptr size_ );
void glTexImage1D (GLenum target_ , GLint level_ , GLint internalformat_ , GLsizei width_ , GLint border_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTexImage2D (GLenum target_ , GLint level_ , GLint internalformat_ , GLsizei width_ , GLsizei height_ , GLint border_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTexImage3D (GLenum target_ , GLint level_ , GLint internalformat_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLint border_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTexParameterIiv (GLenum target_ , GLenum pname_ , const GLint * params_ );
void glTexParameterIuiv (GLenum target_ , GLenum pname_ , const GLuint * params_ );
void glTexParameterf (GLenum target_ , GLenum pname_ , GLfloat param_ );
void glTexParameterfv (GLenum target_ , GLenum pname_ , const GLfloat * params_ );
void glTexParameteri (GLenum target_ , GLenum pname_ , GLint param_ );
void glTexParameteriv (GLenum target_ , GLenum pname_ , const GLint * params_ );
void glTexStorage1D (GLenum target_ , GLsizei levels_ , GLenum internalformat_ , GLsizei width_ );
void glTexStorage2D (GLenum target_ , GLsizei levels_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ );
void glTexStorage3D (GLenum target_ , GLsizei levels_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ );
void glTexSubImage1D (GLenum target_ , GLint level_ , GLint xoffset_ , GLsizei width_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTexSubImage2D (GLenum target_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLsizei width_ , GLsizei height_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTexSubImage3D (GLenum target_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTextureBarrier ();
void glTextureBuffer (GLuint texture_ , GLenum internalformat_ , GLuint buffer_ );
void glTextureBufferRange (GLuint texture_ , GLenum internalformat_ , GLuint buffer_ , GLintptr offset_ , GLsizeiptr size_ );
void glTextureParameterIiv (GLuint texture_ , GLenum pname_ , const GLint * params_ );
void glTextureParameterIuiv (GLuint texture_ , GLenum pname_ , const GLuint * params_ );
void glTextureParameterf (GLuint texture_ , GLenum pname_ , GLfloat param_ );
void glTextureParameterfv (GLuint texture_ , GLenum pname_ , const GLfloat * param_ );
void glTextureParameteri (GLuint texture_ , GLenum pname_ , GLint param_ );
void glTextureParameteriv (GLuint texture_ , GLenum pname_ , const GLint * param_ );
void glTextureStorage1D (GLuint texture_ , GLsizei levels_ , GLenum internalformat_ , GLsizei width_ );
void glTextureStorage2D (GLuint texture_ , GLsizei levels_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ );
void glTextureStorage3D (GLuint texture_ , GLsizei levels_ , GLenum internalformat_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ );
void glTextureSubImage1D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLsizei width_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTextureSubImage2D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLsizei width_ , GLsizei height_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTextureSubImage3D (GLuint texture_ , GLint level_ , GLint xoffset_ , GLint yoffset_ , GLint zoffset_ , GLsizei width_ , GLsizei height_ , GLsizei depth_ , GLenum format_ , GLenum type_ , const void * pixels_ );
void glTextureView (GLuint texture_ , GLenum target_ , GLuint origtexture_ , GLenum internalformat_ , GLuint minlevel_ , GLuint numlevels_ , GLuint minlayer_ , GLuint numlayers_ );
void glTransformFeedbackBufferBase (GLuint xfb_ , GLuint index_ , GLuint buffer_ );
void glTransformFeedbackBufferRange (GLuint xfb_ , GLuint index_ , GLuint buffer_ , GLintptr offset_ , GLsizeiptr size_ );
void glTransformFeedbackVaryings (GLuint program_ , GLsizei count_ , const GLchar ** varyings_ , GLenum bufferMode_ );
void glUniform1d (GLint location_ , GLdouble x_ );
void glUniform1dv (GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glUniform1f (GLint location_ , GLfloat v0_ );
void glUniform1fv (GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glUniform1i (GLint location_ , GLint v0_ );
void glUniform1iv (GLint location_ , GLsizei count_ , const GLint * value_ );
void glUniform1ui (GLint location_ , GLuint v0_ );
void glUniform1uiv (GLint location_ , GLsizei count_ , const GLuint * value_ );
void glUniform2d (GLint location_ , GLdouble x_ , GLdouble y_ );
void glUniform2dv (GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glUniform2f (GLint location_ , GLfloat v0_ , GLfloat v1_ );
void glUniform2fv (GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glUniform2i (GLint location_ , GLint v0_ , GLint v1_ );
void glUniform2iv (GLint location_ , GLsizei count_ , const GLint * value_ );
void glUniform2ui (GLint location_ , GLuint v0_ , GLuint v1_ );
void glUniform2uiv (GLint location_ , GLsizei count_ , const GLuint * value_ );
void glUniform3d (GLint location_ , GLdouble x_ , GLdouble y_ , GLdouble z_ );
void glUniform3dv (GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glUniform3f (GLint location_ , GLfloat v0_ , GLfloat v1_ , GLfloat v2_ );
void glUniform3fv (GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glUniform3i (GLint location_ , GLint v0_ , GLint v1_ , GLint v2_ );
void glUniform3iv (GLint location_ , GLsizei count_ , const GLint * value_ );
void glUniform3ui (GLint location_ , GLuint v0_ , GLuint v1_ , GLuint v2_ );
void glUniform3uiv (GLint location_ , GLsizei count_ , const GLuint * value_ );
void glUniform4d (GLint location_ , GLdouble x_ , GLdouble y_ , GLdouble z_ , GLdouble w_ );
void glUniform4dv (GLint location_ , GLsizei count_ , const GLdouble * value_ );
void glUniform4f (GLint location_ , GLfloat v0_ , GLfloat v1_ , GLfloat v2_ , GLfloat v3_ );
void glUniform4fv (GLint location_ , GLsizei count_ , const GLfloat * value_ );
void glUniform4i (GLint location_ , GLint v0_ , GLint v1_ , GLint v2_ , GLint v3_ );
void glUniform4iv (GLint location_ , GLsizei count_ , const GLint * value_ );
void glUniform4ui (GLint location_ , GLuint v0_ , GLuint v1_ , GLuint v2_ , GLuint v3_ );
void glUniform4uiv (GLint location_ , GLsizei count_ , const GLuint * value_ );
void glUniformBlockBinding (GLuint program_ , GLuint uniformBlockIndex_ , GLuint uniformBlockBinding_ );
void glUniformMatrix2dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix2fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix2x3dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix2x3fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix2x4dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix2x4fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix3dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix3fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix3x2dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix3x2fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix3x4dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix3x4fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix4dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix4fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix4x2dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix4x2fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformMatrix4x3dv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLdouble * value_ );
void glUniformMatrix4x3fv (GLint location_ , GLsizei count_ , GLboolean transpose_ , const GLfloat * value_ );
void glUniformSubroutinesuiv (GLenum shadertype_ , GLsizei count_ , const GLuint * indices_ );
GLboolean glUnmapBuffer (GLenum target_ );
GLboolean glUnmapNamedBuffer (GLuint buffer_ );
void glUseProgram (GLuint program_ );
void glUseProgramStages (GLuint pipeline_ , GLbitfield stages_ , GLuint program_ );
void glValidateProgram (GLuint program_ );
void glValidateProgramPipeline (GLuint pipeline_ );
void glVertexArrayAttribBinding (GLuint vaobj_ , GLuint attribindex_ , GLuint bindingindex_ );
void glVertexArrayAttribFormat (GLuint vaobj_ , GLuint attribindex_ , GLint size_ , GLenum type_ , GLboolean normalized_ , GLuint relativeoffset_ );
void glVertexArrayBindingDivisor (GLuint vaobj_ , GLuint bindingindex_ , GLuint divisor_ );
void glVertexArrayElementBuffer (GLuint vaobj_ , GLuint buffer_ );
void glVertexArrayVertexBuffer (GLuint vaobj_ , GLuint bindingindex_ , GLuint buffer_ , GLintptr offset_ , GLsizei stride_ );
void glVertexArrayVertexBuffers (GLuint vaobj_ , GLuint first_ , GLsizei count_ , const GLuint * buffers_ , const GLintptr * offsets_ , const GLsizei * strides_ );
void glVertexAttrib1d (GLuint index_ , GLdouble x_ );
void glVertexAttrib1dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttrib1f (GLuint index_ , GLfloat x_ );
void glVertexAttrib1fv (GLuint index_ , const GLfloat * v_ );
void glVertexAttrib1s (GLuint index_ , GLshort x_ );
void glVertexAttrib1sv (GLuint index_ , const GLshort * v_ );
void glVertexAttrib2d (GLuint index_ , GLdouble x_ , GLdouble y_ );
void glVertexAttrib2dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttrib2f (GLuint index_ , GLfloat x_ , GLfloat y_ );
void glVertexAttrib2fv (GLuint index_ , const GLfloat * v_ );
void glVertexAttrib2s (GLuint index_ , GLshort x_ , GLshort y_ );
void glVertexAttrib2sv (GLuint index_ , const GLshort * v_ );
void glVertexAttrib3d (GLuint index_ , GLdouble x_ , GLdouble y_ , GLdouble z_ );
void glVertexAttrib3dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttrib3f (GLuint index_ , GLfloat x_ , GLfloat y_ , GLfloat z_ );
void glVertexAttrib3fv (GLuint index_ , const GLfloat * v_ );
void glVertexAttrib3s (GLuint index_ , GLshort x_ , GLshort y_ , GLshort z_ );
void glVertexAttrib3sv (GLuint index_ , const GLshort * v_ );
void glVertexAttrib4Nbv (GLuint index_ , const GLbyte * v_ );
void glVertexAttrib4Niv (GLuint index_ , const GLint * v_ );
void glVertexAttrib4Nsv (GLuint index_ , const GLshort * v_ );
void glVertexAttrib4Nub (GLuint index_ , GLubyte x_ , GLubyte y_ , GLubyte z_ , GLubyte w_ );
void glVertexAttrib4Nubv (GLuint index_ , const GLubyte * v_ );
void glVertexAttrib4Nuiv (GLuint index_ , const GLuint * v_ );
void glVertexAttrib4Nusv (GLuint index_ , const GLushort * v_ );
void glVertexAttrib4bv (GLuint index_ , const GLbyte * v_ );
void glVertexAttrib4d (GLuint index_ , GLdouble x_ , GLdouble y_ , GLdouble z_ , GLdouble w_ );
void glVertexAttrib4dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttrib4f (GLuint index_ , GLfloat x_ , GLfloat y_ , GLfloat z_ , GLfloat w_ );
void glVertexAttrib4fv (GLuint index_ , const GLfloat * v_ );
void glVertexAttrib4iv (GLuint index_ , const GLint * v_ );
void glVertexAttrib4s (GLuint index_ , GLshort x_ , GLshort y_ , GLshort z_ , GLshort w_ );
void glVertexAttrib4sv (GLuint index_ , const GLshort * v_ );
void glVertexAttrib4ubv (GLuint index_ , const GLubyte * v_ );
void glVertexAttrib4uiv (GLuint index_ , const GLuint * v_ );
void glVertexAttrib4usv (GLuint index_ , const GLushort * v_ );
void glVertexAttribBinding (GLuint attribindex_ , GLuint bindingindex_ );
void glVertexAttribDivisor (GLuint index_ , GLuint divisor_ );
void glVertexAttribFormat (GLuint attribindex_ , GLint size_ , GLenum type_ , GLboolean normalized_ , GLuint relativeoffset_ );
void glVertexAttribI1i (GLuint index_ , GLint x_ );
void glVertexAttribI1iv (GLuint index_ , const GLint * v_ );
void glVertexAttribI1ui (GLuint index_ , GLuint x_ );
void glVertexAttribI1uiv (GLuint index_ , const GLuint * v_ );
void glVertexAttribI2i (GLuint index_ , GLint x_ , GLint y_ );
void glVertexAttribI2iv (GLuint index_ , const GLint * v_ );
void glVertexAttribI2ui (GLuint index_ , GLuint x_ , GLuint y_ );
void glVertexAttribI2uiv (GLuint index_ , const GLuint * v_ );
void glVertexAttribI3i (GLuint index_ , GLint x_ , GLint y_ , GLint z_ );
void glVertexAttribI3iv (GLuint index_ , const GLint * v_ );
void glVertexAttribI3ui (GLuint index_ , GLuint x_ , GLuint y_ , GLuint z_ );
void glVertexAttribI3uiv (GLuint index_ , const GLuint * v_ );
void glVertexAttribI4bv (GLuint index_ , const GLbyte * v_ );
void glVertexAttribI4i (GLuint index_ , GLint x_ , GLint y_ , GLint z_ , GLint w_ );
void glVertexAttribI4iv (GLuint index_ , const GLint * v_ );
void glVertexAttribI4sv (GLuint index_ , const GLshort * v_ );
void glVertexAttribI4ubv (GLuint index_ , const GLubyte * v_ );
void glVertexAttribI4ui (GLuint index_ , GLuint x_ , GLuint y_ , GLuint z_ , GLuint w_ );
void glVertexAttribI4uiv (GLuint index_ , const GLuint * v_ );
void glVertexAttribI4usv (GLuint index_ , const GLushort * v_ );
void glVertexAttribL1d (GLuint index_ , GLdouble x_ );
void glVertexAttribL1dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttribL2d (GLuint index_ , GLdouble x_ , GLdouble y_ );
void glVertexAttribL2dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttribL3d (GLuint index_ , GLdouble x_ , GLdouble y_ , GLdouble z_ );
void glVertexAttribL3dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttribL4d (GLuint index_ , GLdouble x_ , GLdouble y_ , GLdouble z_ , GLdouble w_ );
void glVertexAttribL4dv (GLuint index_ , const GLdouble * v_ );
void glVertexAttribP1ui (GLuint index_ , GLenum type_ , GLboolean normalized_ , GLuint value_ );
void glVertexAttribP1uiv (GLuint index_ , GLenum type_ , GLboolean normalized_ , const GLuint * value_ );
void glVertexAttribP2ui (GLuint index_ , GLenum type_ , GLboolean normalized_ , GLuint value_ );
void glVertexAttribP2uiv (GLuint index_ , GLenum type_ , GLboolean normalized_ , const GLuint * value_ );
void glVertexAttribP3ui (GLuint index_ , GLenum type_ , GLboolean normalized_ , GLuint value_ );
void glVertexAttribP3uiv (GLuint index_ , GLenum type_ , GLboolean normalized_ , const GLuint * value_ );
void glVertexAttribP4ui (GLuint index_ , GLenum type_ , GLboolean normalized_ , GLuint value_ );
void glVertexAttribP4uiv (GLuint index_ , GLenum type_ , GLboolean normalized_ , const GLuint * value_ );
void glVertexAttribPointer (GLuint index_ , GLint size_ , GLenum type_ , GLboolean normalized_ , GLsizei stride_ , const void * pointer_ );
void glVertexBindingDivisor (GLuint bindingindex_ , GLuint divisor_ );
void glViewport (GLint x_ , GLint y_ , GLsizei width_ , GLsizei height_ );
void glViewportArrayv (GLuint first_ , GLsizei count_ , const GLfloat * v_ );
void glViewportIndexedf (GLuint index_ , GLfloat x_ , GLfloat y_ , GLfloat w_ , GLfloat h_ );
void glViewportIndexedfv (GLuint index_ , const GLfloat * v_ );
void glWaitSync (GLsync sync_ , GLbitfield flags_ , GLuint64 timeout_ );
